departments/urls.py
from django.conf.urls import url

from . import views

app_name = 'departments'

urlpatterns = [
    url(r'create_message/$', views.CreateMessage.as_view(), name='create_message'),
    url(r'success/$', views.SuccessMessage.as_view(), name='success_message'),
    url(r'csv/$', views.some_view, name='csv'),
]

pesankeluar/urls.py
from django.contrib import admin
from django.urls import path
from django.conf.urls import include, url
from django.contrib.staticfiles.urls import staticfiles_urlpatterns

from . import views

urlpatterns = [
    url(r'^departments/', include('departments.urls', namespace='departments')),
    path('admin/', admin.site.urls),
    url(r'^$', views.Home.as_view(), name='home'),
]

urlpatterns += staticfiles_urlpatterns()

departments/models.py
from django.db import models


class Department(models.Model):
    name = models.CharField(max_length=140, unique=True)

    def __str__(self):
        return self.name


class Division(models.Model):
    name = models.CharField(max_length=140)
    department = models.ForeignKey(Department, on_delete=models.DO_NOTHING)

    def __str__(self):
        return self.name


class Message(models.Model):
    nomor = models.CharField(max_length=255)
    name = models.CharField(max_length=140)
    dep = models.CharField(max_length=100, verbose_name="Department")
    div = models.CharField(max_length=100, verbose_name="Division")
    division = models.ForeignKey(Division, on_delete=models.DO_NOTHING)

    def __str__(self):
        return self.nomor

departments/views.py
from django.http import HttpResponse
from django.shortcuts import render, get_object_or_404
from django.urls import reverse_lazy
from django.views import generic

from datetime import datetime

import xlwt

from . import models


def int_to_Roman(num):
    val = [
        1000, 900, 500, 400,
        100, 90, 50, 40,
        10, 9, 5, 4,
        1
    ]
    syb = [
        "M", "CM", "D", "CD",
        "C", "XC", "L", "XL",
        "X", "IX", "V", "IV",
        "I"
    ]
    roman_num = ''
    i = 0
    while  num > 0:
        for _ in range(num // val[i]):
            roman_num += syb[i]
            num -= val[i]
        i += 1
    return roman_num


class CreateMessage(generic.CreateView):
    fields = ("name", "dep", "div")
    model = models.Message
    success_url = reverse_lazy('departments:success_message')
    

    def form_valid(self, form):
        self.object = form.save(commit=False)
        try:
            depart = models.Department.objects.get(name__iexact=form.cleaned_data['dep'])
        except models.Department.DoesNotExist:
            depart = models.Department.objects.create(name=form.cleaned_data['dep'])
            try:
                models.Division.objects.get(name__iexact=form.cleaned_data['div'], department_id=depart.pk)
            except models.Division.DoesNotExist:
                models.Division.objects.create(name=form.cleaned_data['div'], department=depart)
        else:
            try:
                models.Division.objects.get(name__iexact=form.cleaned_data['div'],
                                            department__name__iexact=form.cleaned_data['dep'])
            except models.Division.DoesNotExist:
                models.Division.objects.create(name=form.cleaned_data['div'], department=depart)
        division = models.Division.objects.get(name__iexact=form.cleaned_data['div'], 
                                               department__name__iexact=form.cleaned_data['dep'])
        no = division.message_set.all().count() + 1
        self.object.nomor = "{0:03d}/{1}-{2}/{3}/{4}".format(no,
            form.cleaned_data['dep'],
            form.cleaned_data['div'],
            int_to_Roman(datetime.now().month),
            datetime.now().year)
        self.object.division = division
        self.object.save()    
        return super().form_valid(form)
        

class SuccessMessage(generic.TemplateView):
    template_name = 'departments/success_message.html'

    def get_context_data(self, **kwargs):
        context = super().get_context_data(**kwargs)
        context['message'] = models.Message.objects.latest('id')
        return context


def some_view(request):
    response = HttpResponse(content_type='application/ms-excel')
    response['Content-Disposition'] = "attachment; filename=messages.xls"
    
    wb = xlwt.Workbook(encoding='utf-8')
    ws = wb.add_sheet('Messages')

    row_num = 0

    font_style = xlwt.XFStyle()
    font_style.font.bold = True

    columns = ['Nomor Surat', 'Departemen', 'Divisi', 'Nama Pengirim',]

    for col_num in range(len(columns)):
        ws.write(row_num, col_num, columns[col_num], font_style)
    
    # Sheet body, remaining rows
    font_style = xlwt.XFStyle()

    rows = models.Message.objects.all().values_list('nomor', 'dep', 'div', 'name')
    for row in rows:
        row_num += 1
        for col_num in range(len(row)):
            ws.write(row_num, col_num, row[col_num], font_style)

    wb.save(response)

    return response

pesankeluar/views.py
from django.views.generic import TemplateView


class Home(TemplateView):
    template_name = 'home.html'

departments/templates/departments/five_last_message.html
{% if messages %}
    <thead>
        <tr>
            <th scope="col" class="text-center">Nomor Surat</th>
            <th scope="col" class="text-center">Departemen</th>
            <th scope="col" class="text-center">Divisi</th>
            <th scope="col" class="text-center">Nama Pengirim</th>
        </tr>
    </thead>
    <tbody class="order">
        {% for message in messages %}
            <tr>
                <td class="text-center">{{ message.nomor }}</td>
                <td class="text-center">{{ message.dep }}</td>
                <td class="text-center">{{ message.div }}</td>
                <td class="text-center">{{ message.name }}</td>
            </tr>
        {% endfor %}
    </tbody>
{% endif %}

departments/templates/departments/last_message.html
{{ message.nomor }}

departments/templates/departments/message_form.html
{% extends 'layout.html' %}
{% load bootstrap3 %}
{% load department_tags %}

{% block wrapper_class %}posts-wrapper{% endblock %}

{% block body_content %}
    <div class="container">
        <h4>New Message</h4>
        <form method="POST">
            {% csrf_token %}
            {% bootstrap_form form %}
            <input type="submit" value="Send" class="btn btn-primary btn-large">
            <a href="{% url 'home' %}" class="btn btn-primary btn-large">Cancel</a>
                <table role="grid" class="stack hover" style="width: 100%; border: 1px solid; margin-top: 50px; margin-bottom: 100px">
                    {% five_last_message %}
                </table>
        </form>
{% endblock %}

departments/templates/departments/success_message.html
{% extends 'layout.html' %}
{% load department_tags %}

{% block body_content %}
    <div class="container">
        <h4>Nomor Surat:</h4>
        <p>{% last_message %}</p>
        <h4>Dari:</h4>
        <p>{{ message.name }}</p>
    </div>
{% endblock %}

templates/home.html
{% extends 'layout.html' %}
{% load static from staticfiles %}

{% block wrapper_class %}posts-wrapper{% endblock %}

{% block body_content %}
<body style="margin-bottom: 0px">
    <div class="landing-header" style="background-image: url('{% static "img/jump.jpg" %}');">
        <div class="container">
            <div class="motto">
                <img src="{% static 'img/icons/email_019-reply-envelope-send-arrow-512.png' %}" style="width: 10%;height: 10%">
                <h4 style="margin-top: -5px">Say something with your new message?</h4>
                <br />
                <div style="margin-top: -20px">
                    <a class="btn" href="{% url 'departments:create_message' %}">Sent?</a>
                    <a class="btn" href="{% url 'departments:csv' %}">Download Database</a>
                </div>
            </div>
        </div>
    </div>
</body>
{% endblock %}

templates/layout.html
{% load static from staticfiles %}
<!DOCTYPE html>
<html lang="en">
    <head>
        <meta charset="utf-8" />
        <meta http-equiv="X-UA-Compatible" content="IE=edge,chrome=1">
        <meta content="width=device-width, initial-scale=1.0, maximum-scale=1.0, user-scalable=0" name="viewport">
        <meta name="viewport" content="width=device-width">
        <title>{% block title_tag %}Pesan{% endblock %}</title>
        <!-- fonts -->
        <link href="http://maxcdn.bootstrapcdn.com/font-awesome/4.2.0/css/font-awesome.min.css" rel="stylesheet">
        <link href="http://fonts.googleapis.com/css?family=Montserrat" rel="stylesheet" type="text/css">
        <link href="http://fonts.googleapis.com/css?family=Open+Sans:400,300" rel="stylesheet" type="text/css">
        
        <!-- stylesheets -->
        <link rel="stylesheet" href="{% static 'css/foundation.min.css' %}">
        <link rel="stylesheet" href="https://maxcdn.bootstrapcdn.com/bootstrap/3.3.7/css/bootstrap.min.css" integrity="sha384-BVYiiSIFeK1dGmJRAkycuHAHRg32OmUcww7on3RYdg4Va+PmSTsz/K68vbdEjh4u" crossorigin="anonymous"/>
        <link rel="stylesheet" href="{% static 'css/ct-paper.css' %}">
        <link rel="stylesheet" href="{% static 'css/msg.css' %}">
    </head>
    <body>
        <nav class="navbar navbar-ct-danger navbar-fixed-top" role="navigation" id="navbar">
            <div class="container">
                <!-- Brand and toggle get grouped for better mobile display -->
                <div class="navbar-header">
                    <button type="button" class="navbar-toggle" data-toggle="collapse" data-target="#navigation-2">
                        <span class="sr-only">Toggle navigation</span>
                        <span class="icon-bar"></span>
                        <span class="icon-bar"></span>
                        <span class="icon-bar"></span>
                    </button>
                    <a class="navbar-brand" href="/">
                        <div class="logo-container">
                            <div class="logo"><img src="{% static 'img/icons/logo.png' %}"></div>
                            <p class="brand">Home</p>
                        </div>
                    </a>
                </div>
            </div><!-- /.container-->
        </nav>

        <div class="wrapper {% block wrapper_class %}{% endblock %}">

            {% if messages %}
                <div class="messages">
                    {% for message in messages %}
                        <div class="alert {% if message.tags %}alert-{{ message.tags }}{% endif %}">
                            <div class="container">{{ message|safe }}</div>
                        </div>
                    {% endfor %}
                </div>
            {% endif %}

            {% block body_content %}{% endblock %}
        </div>

        <footer class="footer section-dark">
            <div class="container">
                <div class="copyright pull-right">
                    &copy; 2019, made with <i class="fa fa-heart heart"></i>
                </div>
            </div>
        </footer>

        <script src="{% static 'js/jquery-1.10.2.js' %}" type="text/javascript"></script>
        <script src="{% static 'js/jquery-ui-1.10.4.custom.min.js' %}" type="text/javascript"></script>

        <script src="https://maxcdn.bootstrapcdn.com/bootstrap/3.3.7/js/bootstrap.min.js" integrity="sha384-Tc5IQib027qvyjSMfHjOMaLkfuWVxZxUPnCJA7l2mCWNIpG9mGCD8wGNIcPD7Txa" crossorigin="anonymous"></script>

        <!--  Plugins -->
		<script src="{% static 'js/ct-paper-checkbox.js' %}"></script>
		<script src="{% static 'js/ct-paper-radio.js' %}"></script>
		<script src="{% static 'js/bootstrap-select.js' %}"></script>
		<script src="{% static 'js/bootstrap-datepicker.js' %}"></script>

		<script src="{% static 'js/ct-paper.js' %}"></script>
    </body>
</html>